import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "@/components/common/nav/Navbar";
import { MenuList } from "@/constants/menu";
import Footer from "@/components/common/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <Navbar menu={MenuList} />
        <main className="flex flex-col items-center justify-between overflow-x-hidden">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
